FROM php:8.2.28-fpm
WORKDIR /var/www/html


EXPOSE 9000



LABEL description="Esta imagem contém um ambiente básico PHP 8.2 com Apache para desenvolvimento." \
      version="1.2-beta" \
      author="Tokyo script <tokyo@email.com>" \
      maintainer="Emanuel <emanoel.0@eu.com>" \
      build-date="2025-05-04"
